# Generated by Django 6.0 on 2025-12-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'unique_together': {('row', 'col')},
            },
        ),
    ]
