# Generated by Django 6.0 on 2025-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='level',
            name='grid',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='level',
            name='col',
        ),
        migrations.RemoveField(
            model_name='level',
            name='row',
        ),
        migrations.RemoveField(
            model_name='level',
            name='value',
        ),
    ]
