# Generated by Django 6.0 on 2025-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_level_unique_together_level_grid_level_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='grid',
        ),
        migrations.AddField(
            model_name='level',
            name='row1',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row2',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row3',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row4',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row5',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row6',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row7',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row8',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
        migrations.AddField(
            model_name='level',
            name='row9',
            field=models.IntegerField(default=0, max_length=999999999),
        ),
    ]
