# Generated by Django 5.2 on 2026-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_authorprofile_book_chapter_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='handpicked',
            field=models.BooleanField(default=False),
        ),
    ]
