# Generated by Django 5.2.10 on 2026-01-30 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_contest_alter_book_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
