# Generated by Django 5.2.10 on 2026-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
