# Generated by Django 5.2.10 on 2026-01-31 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_script_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_poems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_scripts', to=settings.AUTH_USER_MODEL),
        ),
    ]
