# Generated by Django 5.2.10 on 2026-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_poem_bookmarks_script_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='contests', to='newapp.book'),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Script', 'Script'), ('Poem', 'Poem')], default='Book', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='contestors',
            field=models.ManyToManyField(blank=True, related_name='contests', to='newapp.poem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='scripts',
            field=models.ManyToManyField(blank=True, related_name='contests', to='newapp.script'),
        ),
    ]
