# Generated by Django 5.2.10 on 2026-02-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_contest_books_contest_contest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winning_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to='newapp.book'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winning_poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to='newapp.poem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winning_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to='newapp.script'),
        ),
    ]
