# Generated by Django 5.2.10 on 2026-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_authorprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='books',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contestors',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='scripts',
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_books',
            field=models.ManyToManyField(blank=True, related_name='contest_entries', to='newapp.book'),
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_poems',
            field=models.ManyToManyField(blank=True, related_name='contest_entries', to='newapp.poem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_scripts',
            field=models.ManyToManyField(blank=True, related_name='contest_entries', to='newapp.script'),
        ),
    ]
