# Generated by Django 5.2.10 on 2026-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_rename_contest_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FINISHED', 'Finished')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='poem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FINISHED', 'Finished')], default='DRAFT', max_length=10),
        ),
    ]
