# Generated by Django 5.2.10 on 2026-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='scripts/'),
        ),
    ]
