# Generated by Django 5.2.10 on 2026-03-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_bookreview_bookreviewcomment_bookreviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='newapp.profilecomment'),
        ),
    ]
