# Generated by Django 5.2 on 2026-07-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_script_script_format_alter_book_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='entry_books',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='entry_poems',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='entry_scripts',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='winning_book',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='winning_poem',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='winning_script',
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='winning_entry_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('SCRIPT', 'Script'), ('POEM', 'Poem')], default='BOOK', max_length=10),
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('BOOK', 'Book'), ('SCRIPT', 'Script'), ('POEM', 'Poem')], max_length=10)),
                ('entry_id', models.PositiveIntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='newapp.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
